name: build

on:
  push:
    tags:
    - 'v*' 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get ClickHouse
      run: |
        wget https://repo.clickhouse.tech/rpm/stable/x86_64/clickhouse-client-20.5.2.7-2.noarch.rpm
        wget https://repo.clickhouse.tech/rpm/stable/x86_64/clickhouse-common-static-20.5.2.7-2.x86_64.rpm
        wget https://repo.clickhouse.tech/rpm/stable/x86_64/clickhouse-server-20.5.2.7-2.noarch.rpm

    - name: Upload ClickHouse Client
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clickhouse-client-20.5.2.7-2.noarch.rpm
        asset_name: clickhouse-client-20.5.2.7-2.noarch.rpm
        asset_content_type: application/zip

    - name: Upload ClickHouse Common
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clickhouse-common-static-20.5.2.7-2.x86_64.rpm
        asset_name: clickhouse-common-static-20.5.2.7-2.x86_64.rpm
        asset_content_type: application/zip

    - name: Upload ClickHouse Server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clickhouse-server-20.5.2.7-2.noarch.rpm
        asset_name: clickhouse-server-20.5.2.7-2.noarch.rpm
        asset_content_type: application/zip

    - name: Get HAProxy
      run: |
        wget http://www.haproxy.com/download/haproxy/haproxy/centos-8/x86_64/pool/haproxy-2.3.2-23.0.rhel-8.x86_64.rpm

    - name: Upload HAProxy
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./haproxy-2.3.2-23.0.rhel-8.x86_64.rpm
        asset_name: haproxy-2.3.2-23.0.rhel-8.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Mosquitto
      run: |
        wget https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/m/mosquitto-1.6.10-1.el8.x86_64.rpm

    - name: Upload Mosquitto
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mosquitto-1.6.10-1.el8.x86_64.rpm
        asset_name: mosquitto-1.6.10-1.el8.x86_64.rpm
        asset_content_type: application/zip

    - name: Get NGINX
      run: |
        wget https://nginx.org/packages/centos/8/x86_64/RPMS/nginx-1.18.0-2.el8.ngx.x86_64.rpm

    - name: Upload NGINX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nginx-1.18.0-2.el8.ngx.x86_64.rpm
        asset_name: nginx-1.18.0-2.el8.ngx.x86_64.rpm
        asset_content_type: application/zip

    - name: Get OpenJDK
      run: |
        wget https://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/8/x86_64/Packages/adoptopenjdk-11-hotspot-jre-11.0.9+11.2-3.x86_64.rpm

    - name: Upload OpenJDK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./adoptopenjdk-11-hotspot-jre-11.0.9+11.2-3.x86_64.rpm
        asset_name: adoptopenjdk-11-hotspot-jre-11.0.9+11.2-3.x86_64.rpm
        asset_content_type: application/zip

    - name: Get PostgreSQL
      run: |
        wget https://yum.postgresql.org/9.5/redhat/rhel-8-x86_64/postgresql95-9.5.24-1PGDG.rhel8.x86_64.rpm
        wget https://yum.postgresql.org/9.5/redhat/rhel-8-x86_64/postgresql95-libs-9.5.24-1PGDG.rhel8.x86_64.rpm
        wget https://yum.postgresql.org/9.5/redhat/rhel-8-x86_64/postgresql95-server-9.5.24-1PGDG.rhel8.x86_64.rpm

    - name: Upload PostgreSQL
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postgresql95-9.5.24-1PGDG.rhel8.x86_64.rpm
        asset_name: postgresql95-9.5.24-1PGDG.rhel8.x86_64.rpm
        asset_content_type: application/zip

    - name: Upload PostgreSQL Libs
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postgresql95-libs-9.5.24-1PGDG.rhel8.x86_64.rpm
        asset_name: postgresql95-libs-9.5.24-1PGDG.rhel8.x86_64.rpm
        asset_content_type: application/zip

    - name: Upload PostgreSQL Server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postgresql95-server-9.5.24-1PGDG.rhel8.x86_64.rpm
        asset_name: postgresql95-server-9.5.24-1PGDG.rhel8.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Redis
      run: |
        wget http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/redis-5.0.3-2.module_el8.2.0+318+3d7e67ea.x86_64.rpm

    - name: Upload Redis
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./redis-5.0.3-2.module_el8.2.0+318+3d7e67ea.x86_64.rpm
        asset_name: redis-5.0.3-2.module_el8.2.0+318+3d7e67ea.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Suricata
      run: |
        wget https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/s/suricata-5.0.7-1.el8.x86_64.rpm

    - name: Upload Suricata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./suricata-5.0.7-1.el8.x86_64.rpm
        asset_name: suricata-5.0.7-1.el8.x86_64.rpm
        asset_content_type: application/zip
