name: build

on:
  push:
    tags:
    - 'v*' 

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get ClickHouse
      run: |
        wget https://repo.clickhouse.tech/rpm/stable/x86_64/clickhouse-client-20.5.2.7-2.noarch.rpm
        wget https://repo.clickhouse.tech/rpm/stable/x86_64/clickhouse-common-static-20.5.2.7-2.x86_64.rpm
        wget https://repo.clickhouse.tech/rpm/stable/x86_64/clickhouse-server-20.5.2.7-2.noarch.rpm

    - name: Upload ClickHouse Client
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clickhouse-client-20.5.2.7-2.noarch.rpm
        asset_name: clickhouse-client-20.5.2.7-2.noarch.rpm
        asset_content_type: application/zip

    - name: Upload ClickHouse Common
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clickhouse-common-static-20.5.2.7-2.x86_64.rpm
        asset_name: clickhouse-common-static-20.5.2.7-2.x86_64.rpm
        asset_content_type: application/zip

    - name: Upload ClickHouse Server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./clickhouse-server-20.5.2.7-2.noarch.rpm
        asset_name: clickhouse-server-20.5.2.7-2.noarch.rpm
        asset_content_type: application/zip

    - name: Get HAProxy
      run: |
        wget https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/h/haproxy18-1.8.27-1.el7.x86_64.rpm

    - name: Upload HAProxy
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./haproxy18-1.8.27-1.el7.x86_64.rpm
        asset_name: haproxy18-1.8.27-1.el7.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Mosquitto
      run: |
        wget https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/m/mosquitto-1.6.10-1.el7.x86_64.rpm

    - name: Upload Mosquitto
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mosquitto-1.6.10-1.el7.x86_64.rpm
        asset_name: mosquitto-1.6.10-1.el7.x86_64.rpm
        asset_content_type: application/zip

    - name: Get NGINX
      run: |
        wget http://nginx.org/packages/mainline/centos/7/x86_64/RPMS/nginx-1.21.4-1.el7.ngx.x86_64.rpm

    - name: Upload NGINX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./nginx-1.21.4-1.el7.ngx.x86_64.rpm
        asset_name: nginx-1.21.4-1.el7.ngx.x86_64.rpm
        asset_content_type: application/zip

    - name: Get OpenJDK
      run: |
        wget -O adoptopenjdk-11-hotspot-jre-11.0.9+11.2-3.x86_64.rpm 'https://adoptopenjdk.jfrog.io/ui/api/v1/download?repoKey=rpm&path=centos%2F7%2Fx86_64%2FPackages%2Fadoptopenjdk-11-hotspot-jre-11.0.9%2B11.2-3.x86_64.rpm'

    - name: Upload OpenJDK
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./adoptopenjdk-11-hotspot-jre-11.0.9+11.2-3.x86_64.rpm
        asset_name: adoptopenjdk-11-hotspot-jre-11.0.9+11.2-3.x86_64.rpm
        asset_content_type: application/zip

    - name: Get PostgreSQL
      run: |
        wget https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/postgresql95-9.5.25-1PGDG.rhel7.x86_64.rpm
        wget https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/postgresql95-libs-9.5.25-1PGDG.rhel7.x86_64.rpm
        wget https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/postgresql95-server-9.5.25-1PGDG.rhel7.x86_64.rpm

    - name: Upload PostgreSQL
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postgresql95-9.5.25-1PGDG.rhel7.x86_64.rpm
        asset_name: postgresql95-9.5.25-1PGDG.rhel7.x86_64.rpm
        asset_content_type: application/zip

    - name: Upload PostgreSQL Libs
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postgresql95-libs-9.5.25-1PGDG.rhel7.x86_64.rpm
        asset_name: postgresql95-libs-9.5.25-1PGDG.rhel7.x86_64.rpm
        asset_content_type: application/zip

    - name: Upload PostgreSQL Server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./postgresql95-server-9.5.25-1PGDG.rhel7.x86_64.rpm
        asset_name: postgresql95-server-9.5.25-1PGDG.rhel7.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Redis
      run: |
        wget https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/r/redis-3.2.12-2.el7.x86_64.rpm

    - name: Upload Redis
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./redis-3.2.12-2.el7.x86_64.rpm
        asset_name: redis-3.2.12-2.el7.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Docker
      run: |
        wget https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-20.10.9-3.el7.x86_64.rpm

    - name: Upload Docker
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./docker-ce-20.10.9-3.el7.x86_64.rpm
        asset_name: docker-ce-20.10.9-3.el7.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Suricata
      run: |
        wget https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/s/suricata-4.1.10-1.el7.x86_64.rpm

    - name: Upload Suricata
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./suricata-4.1.10-1.el7.x86_64.rpm
        asset_name: suricata-4.1.10-1.el7.x86_64.rpm
        asset_content_type: application/zip

    - name: Get Fluent Bit
      run: |
        wget https://apt.fluentbit.io/centos/7/x86_64/td-agent-bit-1.7.9-1.x86_64.rpm

    - name: Upload Fluent Bit
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./td-agent-bit-1.7.9-1.x86_64.rpm
        asset_name: td-agent-bit-1.7.9-1.x86_64.rpm
        asset_content_type: application/zip
